import json
import asyncio
from openai import AsyncOpenAI
from google import genai
from google.genai import types
from config import GROQ_API_KEYS, GEMINI_API_KEYS, GROQ_MODELS, GEMINI_MODELS, FORMAT_JSON, FORMAT_TABLE, FORMAT_BULLETS, FORMAT_REPORT
import re

async def evaluate_quality_robust(query: str, final_answer: str) -> dict:
    """
    Cascading Fallback Judge: Evaluates WITHOUT ground truth.
    Relies on expert reasoning, logical consistency check, and Gemini's Search Grounding.
    """
    if not final_answer:
        return {"score": -1.0, "reasoning": "Empty Answer generated by Agent."}

    prompt = f"""
    You are an impartial, rigorous expert fact-checker and evaluator.
    Your task is to evaluate the quality of the 'Actual Answer' in response to the 'Original Question'.
    
    Original Question: {query}
    Actual Answer: {final_answer}
    
    Evaluation Criteria:
    1. Accuracy: Are the claims factually correct?
    2. Completeness: Does it address all constraints and sub-questions of the prompt?
    3. Hallucination: Are there any fabricated facts, fake URLs, or logical contradictions?
    
    First, provide a brief 'reasoning' (max 3 sentences) pointing out any flaws, missing info, or confirming its perfection.
    Then, provide a 'score' strictly from 0.0 (completely wrong/hallucinated) to 1.0 (perfectly accurate and comprehensive).
    """

    # ==========================================
    # 1. GROQ EVALUATION (Primary Fast Path)
    # ==========================================
    groq_system_prompt = "You are an expert evaluator. Output strictly in JSON format: {\"reasoning\": \"string\", \"score\": float}."
    
    for idx, key in enumerate(GROQ_API_KEYS):
        client = AsyncOpenAI(api_key=key, base_url="https://api.groq.com/openai/v1")
        
        for model_name in GROQ_MODELS:
            try:
                response = await client.chat.completions.create(
                    model=model_name,
                    response_format={"type": "json_object"},
                    messages=[
                        {"role": "system", "content": groq_system_prompt},
                        {"role": "user", "content": prompt}
                    ],
                    temperature=0.0
                )
                
                result = json.loads(response.choices[0].message.content)
                if "score" in result and "reasoning" in result:
                    return result
                    
            except Exception as e:
                print(f"  [Groq Judge] Fail: Key {idx+1} | Model {model_name} -> {str(e)[:50]}...")


    # ==========================================
    # 2. GEMINI EVALUATION (Fallback / Grounded Path)
    # ==========================================
    for idx, key in enumerate(GEMINI_API_KEYS):
        client = genai.Client(api_key=key)
        
        for model_name in GEMINI_MODELS:
            try:
                # Using the .aio property for asynchronous generation
                response = await client.aio.models.generate_content(
                    model=model_name,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        temperature=0.0,
                        tools=[{'google_search': {}}], 
                        response_schema={
                            "type": "OBJECT",
                            "properties": {
                                "reasoning": {"type": "STRING"},
                                "score": {"type": "NUMBER"}
                            },
                            "required": ["reasoning", "score"]
                        }
                    )
                )
                
                result = json.loads(response.text)
                if "score" in result and "reasoning" in result:
                    return result
                    
            except Exception as e:
                print(f"  [Google Judge] Fail: Key {idx+1} | Model {model_name} -> {str(e)[:50]}...")


    # ==========================================
    # 3. EXHAUSTION FALLBACK
    # ==========================================
    print("  [CRITICAL] All Google and Groq API keys/models exhausted!")
    return {"score": -1.0, "reasoning": "All API keys and models exhausted or failed to respond."}


def check_format_validity(final_output: str, format_req: str) -> float:
    """
    Rule-based check to verify if the output adheres to the requested format.
    Returns 1.0 (Valid) or 0.0 (Invalid).
    """
    if format_req == FORMAT_JSON:
        try:
            clean_str = final_output.strip().removeprefix("```json").removesuffix("```").strip()
            json.loads(clean_str)
            return 1.0
        except json.JSONDecodeError:
            return 0.0
            
    elif format_req == FORMAT_TABLE:
        if re.search(r'\|[\s\-]+\|', final_output):
            return 1.0
        return 0.0
        
    elif format_req == FORMAT_BULLETS:
        if "\n-" in final_output or "\n*" in final_output:
            return 1.0
        return 0.0
        
    elif format_req == FORMAT_REPORT:
        if "Introduction" in final_output or "Conclusion" in final_output or "Key Findings" in final_output:
            return 1.0
        return 0.0
        
    return 1.0  

def check_citation_hallucination(final_output: str, evidence_texts: list[str]) -> float:
    """
    Cross-checks URLs in the final output against URLs found in the evidence.
    If the LLM hallucinates a fake URL that was not in the search data, returns 0.0.
    Otherwise, returns 1.0.
    """
    url_pattern = r'(https?://[^\s]+)'
    
    output_urls = set(re.findall(url_pattern, final_output))
    if not output_urls:
        return 1.0
        
    evidence_urls = []
    for ev in evidence_texts:
        evidence_urls.extend(re.findall(url_pattern, ev))
    evidence_urls = set(evidence_urls)
    
    for url in output_urls:
        clean_url = url.strip(").,;\"'")
        if not any(clean_url in ev_url for ev_url in evidence_urls):
            return 0.0
            
    return 1.0